using Dapper;
using Oracle.ManagedDataAccess.Client;

namespace docker_oracle;

internal class Program
{
    static void Main(string[] args)
    {
        // string connectionString = "User Id=sys;Password=passw0rd;Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XE)));";
        string connectionString = "User Id=sys;Password=passw0rd;Connection Timeout=0;DBA Privilege=SYSDBA;Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XEPDB1)));";

        using OracleConnection db = new(connectionString);
        //db.KeepAlive = true;
        //db.UseHourOffsetForUnsupportedTimezone = true;

        // テーブルの作成
        var createTableQuery = @"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE SampleTable (
                        Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        Name VARCHAR2(100),
                        Age NUMBER
                    )';
                EXCEPTION
                    WHEN OTHERS THEN
                        IF SQLCODE != -955 THEN
                            RAISE;
                        END IF;
                END;";

        db.Execute(createTableQuery);

        //// データの挿入
        //var insertQuery = "INSERT INTO SampleTable (Name, Age) VALUES (:Name, :Age)";
        //db.Execute(insertQuery, new { Name = "John Doe", Age = 30 });
        //db.Execute(insertQuery, new { Name = "Jane Doe", Age = 25 });

        // データの選択
        var selectQuery = "SELECT * FROM SampleTable";
        var data = db.Query<SampleTable>(selectQuery);

        foreach (var item in data)
        {
            Console.WriteLine($"ID: {item.Id}, Name: {item.Name}, Age: {(int)item.Age}");
        }
    }
}

public class SampleTable
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
}
